In [10]:
# import os
# os.environ['KAGGLE_CONFIG_DIR']='C:/Users/tkeo1/Downloads'

# !kaggle competitions download -c dogs-vs-cats-redux-kernels-edition

In [30]:
import os
os.getcwd()

'C:\\Users\\tkeo1\\OneDrive\\바탕 화면\\coding\\Python\\data'

In [12]:
os.chdir("C:/Users/tkeo1/OneDrive/바탕 화면/coding/Python/data/")

In [27]:
# import zipfile
# zip_file="train.zip"
# extract_to="C:/Users/tkeo1/OneDrive/바탕 화면/coding/Python/data/"
# with zipfile.ZipFile(zip_file,'r') as zip_ref:
#     zip_ref.extractall(extract_to)

In [32]:

import shutil

for i in os.listdir('train/'):
    if 'cat' in i:
        shutil.copyfile('train/' + i,'dataset/cat/' + i )
    if 'dog' in i:
        shutil.copyfile('train/' + i,'dataset/dog/' + i )


In [14]:
import os
print(len(os.listdir('train')))

25000


In [38]:
# import os

# # 검사할 디렉토리 경로를 지정합니다. 백슬래시는 파이썬에서 이스케이프 문자이므로, 경로를 정의할 때 각 백슬래시를 두 번씩 입력하거나 r을 사용하여 raw 문자열을 나타내야 합니다.
# directory = r"C:\Users\tkeo1\OneDrive\바탕 화면\coding\Python\data"

# # 디렉토리의 모든 파일 목록을 가져옵니다.
# for filename in os.listdir(directory):
#     # 파일명에 'cat' 또는 'dog'이 포함되어 있는지 확인합니다.
#     if 'cat' in filename or 'dog' in filename:
#         # 조건에 맞는 파일의 전체 경로를 생성합니다.
#         file_path = os.path.join(directory, filename)
#         try:
#             # 파일을 삭제합니다.
#             os.remove(file_path)
#             print(f"{file_path} has been removed")
#         except Exception as e:
#             # 삭제 중 문제가 발생한 경우 오류 메시지를 출력합니다.
#             print(f"Error occurred while deleting file: {file_path}. Error: {e}")


In [41]:
import tensorflow as tf
train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    'dataset',
    image_size=(64,64),
    batch_size=64,               #이미지 2만장 한번에 넣지 않고 batch 숫자만큼 넣음
    subset='training',
    validation_split=0.2,
    seed=1234
) # 이미지 숫자화 함수 , 폴더 내 이미지들을 바로 dataset 만들어줌

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    'dataset',
    image_size=(64,64),
    batch_size=64,               #이미지 2만장 한번에 넣지 않고 batch 숫자만큼 넣음
    subset='validation',
    validation_split=0.2,
    seed=1234
) # 이미지 숫자화 함수 , 폴더 내 이미지들을 바로 dataset 만들어줌

print(train_ds)

def 전처리함수(i,정답):
    i = tf.cast( i/255.0, tf.float32)
    return i, 정답

train_ds=train_ds.map(전처리함수)
val_ds=val_ds.map(전처리함수)

Found 25000 files belonging to 2 classes.
Using 20000 files for training.
Found 25000 files belonging to 2 classes.
Using 5000 files for validation.
<BatchDataset element_spec=(TensorSpec(shape=(None, 64, 64, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>


In [40]:
# 새로운 경로를 설정합니다. 이 폴더는 미리 생성되어 있어야 합니다.
new_path = "C:\\Users\\tkeo1\\OneDrive\\바탕 화면\\coding\\Python\\data\\validation"

# 파일 경로와 레이블을 가져옵니다.
file_paths = val_ds.file_paths

for file_path in file_paths:
    # 파일을 새 경로로 이동합니다. 이것은 잘라내기 및 붙여넣기 작업에 해당합니다.
    shutil.move(file_path, os.path.join(new_path, os.path.basename(file_path)))

AttributeError: 'MapDataset' object has no attribute 'file_paths'

In [24]:
import matplotlib.pyplot as plt
for i, 정답 in train_ds.take(1):
    print(i)
    print(정답)
#     plt.imshow(i[0].numpy().astype('uint8'))
#     plt.show()

tf.Tensor(
[[[[0.08425054 0.02934857 0.02542701]
   [0.0788603  0.02395833 0.02003676]
   [0.09209559 0.04895834 0.03327206]
   ...
   [0.06710516 0.02360026 0.00803654]
   [0.07450981 0.01960784 0.01568628]
   [0.00392923 0.00803654 0.00392923]]

  [[0.1010972  0.0501168  0.02658739]
   [0.119267   0.06828661 0.0447572 ]
   [0.06590265 0.03845167 0.01492226]
   ...
   [0.07071079 0.02720588 0.01164216]
   [0.06977443 0.01487247 0.0109509 ]
   [0.00349839 0.01146408 0.00509153]]

  [[0.09571078 0.04473039 0.01335784]
   [0.09761029 0.0466299  0.01525735]
   [0.07900965 0.066142   0.03922909]
   ...
   [0.07178692 0.02703546 0.01188726]
   [0.0753753  0.02147863 0.01722197]
   [0.00857843 0.01602137 0.00982307]]

  ...

  [[0.3947572  0.32857114 0.24108073]
   [0.46586245 0.3835095  0.26279873]
   [0.5416322  0.4666322  0.34874004]
   ...
   [0.46569967 0.29682714 0.0887389 ]
   [0.37026656 0.20948224 0.0077742 ]
   [0.4407437  0.29987362 0.05557215]]

  [[0.48482114 0.40479666 0.296574

In [26]:
model=tf.keras.Sequential([
    
    tf.keras.layers.experimental.preprocessing.RandomFlip('horizontal',input_shape=(128,128,3)),
    tf.keras.layers.experimental.preprocessing.RandomRotation(0.1),
    tf.keras.layers.experimental.preprocessing.RandomZoom(0.1),
    
    tf.keras.layers.Conv2D(32,(3,3),padding="same",activation='relu'), #이미지데이터는 0~255 숫자 , 음수 내보내지 않기 위해 // input_shape 컬러사진일때는 28,28,3 (RGB 때문)
    tf.keras.layers.MaxPooling2D((2,2)),
    tf.keras.layers.Conv2D(64,(3,3),padding="same",activation='relu'), #이미지데이터는 0~255 숫자 , 음수 내보내지 않기 위해 // input_shape 컬러사진일때는 28,28,3 (RGB 때문)
    tf.keras.layers.MaxPooling2D((2,2)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Conv2D(128,(3,3),padding="same",activation='relu'), #이미지데이터는 0~255 숫자 , 음수 내보내지 않기 위해 // input_shape 컬러사진일때는 28,28,3 (RGB 때문)
    tf.keras.layers.MaxPooling2D((2,2)),
    # tf.keras.layers.Dense(128,input_shape=(28,28),activation="relu"),
    tf.keras.layers.Flatten(), # 2d data -> 1d data
    tf.keras.layers.Dense(128,activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1,activation="sigmoid"), # convol 2D > pool layer > flatten > dense
])  
#sigmoid = binary prediction (finally number of node = 1)
#softmax = category prediction (finally number of node > 1)
model.summary()

model.compile(loss="binary_crossentropy", optimizer="adam",metrics=['accuracy'])
# sparse_categorical_crossentropy = category prediction 정수로 인코딩 되어있을때 (0,1,2,...)
# categorical_crossentropy = category prediction 는 Y데이터가 원핫인코딩 되어있을때 (0 , 1)

model.fit(train_ds,validation_data=val_ds,epochs=20) # train_ds 형태는 ([이미지],[정답])

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 random_flip (RandomFlip)    (None, 64, 64, 3)         0         
                                                                 
 random_rotation (RandomRota  (None, 64, 64, 3)        0         
 tion)                                                           
                                                                 
 random_zoom (RandomZoom)    (None, 64, 64, 3)         0         
                                                                 
 conv2d_8 (Conv2D)           (None, 64, 64, 32)        896       
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 32, 32, 32)       0         
 2D)                                                             
                                                                 
 conv2d_9 (Conv2D)           (None, 32, 32, 64)       

In [ ]:
# 이미지 증강
from tensorflow.keras.preprocessing.image import ImageDataGenerator

생성기 = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20, #회전
    zoom_range=0.15, #확대
    width_shift_range=0.2, #이동
    height_shift_range=0.2,
    shear_range=0.15, #굴절
    horizontal_flip=True, #가로반전
    fill_mode="nearest")

트레이닝용 = 생성기.flow_from_directory(
    "C:\Users\tkeo1\OneDrive\바탕 화면\coding\Python\data\dataset",
    class_mode='binary', # 두개면 binary, 몇개 더면 categorical
    shuffle=True,
    seed=123,
    color_mode='rgb',
    batch_size=64,
    target_size=(64,64),
)

생성기2 = ImageDataGenerator(rescale=1./255) # validation 데이터는 이미지 뒤틀 필요 없음
검증용 = 생성기2.flow_from_directory(
    "C:\Users\tkeo1\OneDrive\바탕 화면\coding\Python\data\dataset",
    class_mode='binary', # 두개면 binary, 몇개 더면 categorical
    shuffle=True,
    seed=123,
    color_mode='rgb',
    batch_size=64,
    target_size=(64,64),
)

In [ ]:
model=tf.keras.Sequential([
    
    tf.keras.layers.experimental.preprocessing.RandomFlip('horizontal',input_shape=(128,128,3)),
    tf.keras.layers.experimental.preprocessing.RandomRotation(0.1),
    tf.keras.layers.experimental.preprocessing.RandomZoom(0.1),
    
    tf.keras.layers.Conv2D(32,(3,3),padding="same",activation='relu'), #이미지데이터는 0~255 숫자 , 음수 내보내지 않기 위해 // input_shape 컬러사진일때는 28,28,3 (RGB 때문)
    tf.keras.layers.MaxPooling2D((2,2)),
    tf.keras.layers.Conv2D(64,(3,3),padding="same",activation='relu'), #이미지데이터는 0~255 숫자 , 음수 내보내지 않기 위해 // input_shape 컬러사진일때는 28,28,3 (RGB 때문)
    tf.keras.layers.MaxPooling2D((2,2)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Conv2D(128,(3,3),padding="same",activation='relu'), #이미지데이터는 0~255 숫자 , 음수 내보내지 않기 위해 // input_shape 컬러사진일때는 28,28,3 (RGB 때문)
    tf.keras.layers.MaxPooling2D((2,2)),
    # tf.keras.layers.Dense(128,input_shape=(28,28),activation="relu"),
    tf.keras.layers.Flatten(), # 2d data -> 1d data
    tf.keras.layers.Dense(128,activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1,activation="sigmoid"), # convol 2D > pool layer > flatten > dense
])  
#sigmoid = binary prediction (finally number of node = 1)
#softmax = category prediction (finally number of node > 1)
model.summary()

model.compile(loss="binary_crossentropy", optimizer="adam",metrics=['accuracy'])
# sparse_categorical_crossentropy = category prediction 정수로 인코딩 되어있을때 (0,1,2,...)
# categorical_crossentropy = category prediction 는 Y데이터가 원핫인코딩 되어있을때 (0 , 1)

model.fit(트레이닝용,validation_data=검증용,epochs=20) # train_ds 형태는 ([이미지],[정답])