In [1]:
text = open('C:/Users/tkeo1/OneDrive/바탕 화면/coding/Python/data/pianoabc.txt','r').read()
# print(text)

text_uq = list(set(text)) # 리스트랑 비슷한데 중복자료 허용 x
text_uq. sort()
# print(text_uq)

In [2]:
# utilities
text_to_num = {}
num_to_text={}

for i, data in enumerate(text_uq):
    text_to_num[data]=i
    num_to_text[i]=data

# print(text_to_num)
print(num_to_text[3])

/


In [3]:
text_nu=[] # 원본데이터를 숫자로 바꾸기

for i in text:
    text_nu.append(text_to_num[i])

# print(text_nu)

In [4]:
X=[]
Y=[]

for i in range(0,len(text_nu) - 25):
    X.append(text_nu[i:i+25])
    Y.append(text_nu[i+25])

print(X[0:5])
print(Y[0:5])

import numpy as np
print(np.array(X).shape)

[[27, 0, 20, 0, 26, 5, 15, 0, 17, 0, 14, 6, 3, 5, 15, 3, 5, 25, 0, 20, 0, 15, 5, 20, 0], [0, 20, 0, 26, 5, 15, 0, 17, 0, 14, 6, 3, 5, 15, 3, 5, 25, 0, 20, 0, 15, 5, 20, 0, 17], [20, 0, 26, 5, 15, 0, 17, 0, 14, 6, 3, 5, 15, 3, 5, 25, 0, 20, 0, 15, 5, 20, 0, 17, 0], [0, 26, 5, 15, 0, 17, 0, 14, 6, 3, 5, 15, 3, 5, 25, 0, 20, 0, 15, 5, 20, 0, 17, 0, 14], [26, 5, 15, 0, 17, 0, 14, 6, 3, 5, 15, 3, 5, 25, 0, 20, 0, 15, 5, 20, 0, 17, 0, 14, 5]]
[17, 0, 14, 5, 27]
(291997, 25)


In [5]:
# one hot encoding
import tensorflow as tf
X = tf.one_hot(X,31)
Y = tf.one_hot(Y,31)

print(X[0:2])

tf.Tensor(
[[[0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]], shape=(2, 25, 31), dtype=float32)


In [8]:
import os
os.getcwd()

'C:\\Users\\tkeo1\\OneDrive\\바탕 화면\\coding\\Python'

In [11]:
model=tf.keras.models.Sequential([
    tf.keras.layers.LSTM(100,input_shape=(25,31)), # 하나의 데이터 input_shape/ activation function 안넣어도 됨.
    tf.keras.layers.Dense(31,activation='softmax')
])

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy']) # 원핫 인코딩이면 sparse 안써도 됨.
model.fit(X,Y,batch_size=64,epochs=100,verbose=2) #64개 데이터 학습한 후에 w 값 업데이트 일어나게 하고 싶다 / LSTM epoch 많이 해야됨 / 'verbose=2' 파라미터는 학습중 출력되는 것좀 줄이는 것
model.save('model')

Epoch 1/100
4563/4563 - 37s - loss: 1.6017 - accuracy: 0.4982 - 37s/epoch - 8ms/step
Epoch 2/100
4563/4563 - 37s - loss: 1.2947 - accuracy: 0.5743 - 37s/epoch - 8ms/step
Epoch 3/100
4563/4563 - 36s - loss: 1.1982 - accuracy: 0.6055 - 36s/epoch - 8ms/step
Epoch 4/100
4563/4563 - 35s - loss: 1.1398 - accuracy: 0.6256 - 35s/epoch - 8ms/step
Epoch 5/100
4563/4563 - 35s - loss: 1.1021 - accuracy: 0.6383 - 35s/epoch - 8ms/step
Epoch 6/100
4563/4563 - 35s - loss: 1.0733 - accuracy: 0.6469 - 35s/epoch - 8ms/step
Epoch 7/100
4563/4563 - 36s - loss: 1.0500 - accuracy: 0.6543 - 36s/epoch - 8ms/step
Epoch 8/100
4563/4563 - 35s - loss: 1.0299 - accuracy: 0.6614 - 35s/epoch - 8ms/step
Epoch 9/100
4563/4563 - 35s - loss: 1.0130 - accuracy: 0.6662 - 35s/epoch - 8ms/step
Epoch 10/100
4563/4563 - 34s - loss: 0.9984 - accuracy: 0.6708 - 34s/epoch - 8ms/step
Epoch 11/100
4563/4563 - 35s - loss: 0.9843 - accuracy: 0.6757 - 35s/epoch - 8ms/step
Epoch 12/100
4563/4563 - 36s - loss: 0.9724 - accuracy: 0.6794 

INFO:tensorflow:Assets written to: model\assets


INFO:tensorflow:Assets written to: model\assets
